---
title: "S&P500 ML Quant Strategy"
description: "This is a live strategy for investing in 5 stocks from the S&P 500"
date: "2/2/2026"
draft: false
categories:
  - S&P500
  - Machine Learning
  - LightGBM
  - Quant
execute:
  python: /Users/marcusprewarski/projects/venv/bin/python
---

# S&P500 5 ML Quant Strategy

This is a quantitative stock selection strategy. It uses machine learning (ML) models to rank stocks
in the S&P500 and selects the highest ranking ones.

This strategy has been live since November 26 and this chart shows the performance and some basic statistics.
In the chart below the benchmark is the S&P500.

<iframe width="490" height="865" src="https://www.portfolio123.com/embedded_port.jsp?portid=1898665&amp;title=1&amp;stats=1&amp;chartH=475&amp;chartW=440" frameborder="0"></iframe>


These are the holdings as of 2/02/2026.

```{python}
#| echo: false
import pandas as pd

holdings = pd.read_csv("holdings.csv")
holdings.columns = holdings.columns.str.strip()
holdings = holdings.loc[:, ~holdings.columns.str.contains("^Unnamed")]
holdings
```

Below is a table of recent transactions.

```{python}
#| echo: false
import pandas as pd

holdings = pd.read_csv("transactions.csv")
holdings.columns = holdings.columns.str.strip()
holdings = holdings.loc[:, ~holdings.columns.str.contains("^Unnamed")]
holdings
```

There are different components to a quantitative stock selection strategy.

### Stock Universe

The Universe is the group of stocks used in the strategy. This one uses only stocks within the S&P500 index.


### Ranking System

The Ranking System ranks all the stocks in the Universe from best to worst. This one uses a ML model to do the
ranking. The model architecture used is LightGBM which is a kind of boosted regression tree model. It is 
trained on about 70 different features over 15 years of data. The feature set includes a wide variety of data
including value, growth, quality, momentum and sentiment. I will write more about this in a different post.


### Buy/Sell Strategy

Initially, the strategy selects the top 5 ranked stocks from the S&P500. The portfolio is rebalanced once a week. If any stocks ranking falls out of the top 8% then it is sold and replaced by the highest ranked stock
not currently in the portfolio.
